thankloganforserving/thank_logan/urls.py
from django.urls import path

from . import views

app_name = "thank_logan"
urlpatterns = [
    path("", views.index, name="index"),
    path("thank/", views.give_thanks, name="thank"),
]

thankloganforserving/thankloganforserving/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("thank_logan.urls")),
    path("admin/", admin.site.urls),
]

thankloganforserving/thank_logan/models.py
from django.db import models
from django.utils import timezone


class Thank(models.Model):
    timestamp = models.DateTimeField("time of thanks")
    thanker = models.CharField(max_length=100)

    def __str__(self):
        return f"{timezone.localtime(self.timestamp)} - {self.thanker}"


class SMSQueue(models.Model):
    thank = models.ForeignKey(Thank, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.thank.timestamp} - {self.thank.thanker}"

thankloganforserving/thank_logan/views.py
import datetime
import os

import requests
from django.db.models import Count
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone

from .models import SMSQueue, Thank


def _now():
    return timezone.localtime(timezone.now())


def _most_recent_thank():
    return Thank.objects.all().latest("timestamp")


def _thanked_today():
    try:
        most_recent_thank = _most_recent_thank()
        thanked_today = (
            _now().date() == timezone.localtime(most_recent_thank.timestamp).date()
        )
    except Thank.DoesNotExist:
        # this means no thanks on record :(
        thanked_today = False

    return thanked_today


def _current_streak():
    return None


def _longest_streak():
    return None


def _leader_board():
    most_thanks = (
        Thank.objects.values("thanker")
        .annotate(count=Count("thanker"))
        .order_by("-count")
    )[0:5]

    position = 1
    previous_count = None
    for thanker in most_thanks:
        if previous_count is None:
            thanker["position"] = position
        elif thanker["count"] == previous_count:
            thanker["position"] = position
        else:
            position += 1
            thanker["position"] = position

        previous_count = thanker["count"]

    return filter(lambda thanker: thanker["count"] > 1, most_thanks)


def index(request):
    tomorrow = _now() + timezone.timedelta(days=1)
    try:
        most_recent_thanker = _most_recent_thank().thanker
    except Thank.DoesNotExist:
        # this means no thanks on record :(
        most_recent_thanker = None
    context = {
        "thanked": _thanked_today(),
        "tomorrow": tomorrow.date(),
        "most_recent_thanker": most_recent_thanker,
        "current_streak": _current_streak(),
        "longest_streak": _longest_streak(),
        "leader_board": _leader_board(),
    }

    return render(request, "thank_logan/index.html", context)


def give_thanks(request):
    if not _thanked_today():
        thanker = request.POST.get("name", None)
        thank = Thank(timestamp=_now(), thanker=thanker)
        thank.save()

        SMSQueue(thank=thank).save()

    return HttpResponseRedirect(reverse("thank_logan:index"))

thankloganforserving/thank_logan/templates/thank_logan/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'thank_logan/style.css' %}">

<div class="wrapper">
<div id="container">
  <h1>ThankLoganForServing.Us</h1>
  <hr>
<div id=flexcontainer>
<div id=thank class=content>

{% if not thanked %}
<h2> Logan Has Not Been Thanked Today </h2>
<form action="{% url 'thank_logan:thank' %}" method="post">
{% csrf_token %}
<label for="name">Who is thanking Logan?</label><br>
<input type="text" id="name" name="name"><br>
<input type="submit" value="Thank">
</form>


{% else %}
<h2> Logan Has Been Thanked Today </h2>

<p>
Today's thank brought to you by:
</p>

<p id=thanker>
  {{ most_recent_thanker }}
</p>

<p>
<span id="countdown"></span>until he can be thanked again
</p>

<script>
// js sux
// Set the date we're counting down to
var countDownDate = new Date("{{ tomorrow }}").getTime();

function countdown() {
  // Get today's date and time
  var now = new Date().getTime();

  // Find the distance between now and the count down date
  var distance = countDownDate - now;

  // https://stackoverflow.com/a/2998874
  const zeroPad = (num, places) => String(num).padStart(places, '0')

  // Time calculations for days, hours, minutes and seconds
  var hours = zeroPad(Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)), 2);
  var minutes = zeroPad(Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60)), 2);
  var seconds = zeroPad(Math.floor((distance % (1000 * 60)) / 1000), 2);

  // Display the result in the element with id="countdown"
  document.getElementById("countdown").innerHTML = hours + ":" + minutes + ":" + seconds + " ";

  // If the count down is finished, write some text
  if (distance < 0) {
    clearInterval(x);
    location.reload(true);
  }
}

countdown()

// Update the count down every 1 second
setInterval(countdown, 1000);
</script>
{% endif %}
</div>

<div id=stats class=content>
{% comment %}
<div>
<table>
  <tr>
    <th class=title colspan="2">Streaks</th>
  </tr>
  <tr>
    <th>Current</th>
    <td>{{ current_streak }}</td>
  </tr>
  <tr>
    <th>Longest</th>
    <td>{{ longest_streak }}</td>
  </tr>
</table>
</div>
{% endcomment %}

<div>
<table>
  <tr>
    <th class=title colspan="3">Leaderboard</th>
  </tr>
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>Thanks</th>
  </tr>
  {% for thanker in leader_board %}
  <tr>
    <td>{{ thanker.position }}</td>
    <td>{{ thanker.thanker }}</td>
    <td>{{ thanker.count }}</td>
  </tr>
  {% empty %}
  <tr>
    <td>0</td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  {% endfor %}
</table>
</div>
</div>

</div>
<div class=wrapper>
<div id=about class=content>
  <h2>About</h2>
  <p class=text>This website is dedicated to thanking our good friend Logan for serving us. Each day, he can be thanked by one person. At midnight each night it will be possible to thank Logan again. You have to be quick if you want to thank him!</p>
  <h3>Credits</h3>
  <p>This site is only possible because of the following people:</p>
  <ul>
    <li><b>Chad:</b> The idea, funding, emotional support and motivation. </li>
    <li><b>Jack:</b> For finding the background image. </li>
    <li><b>Jordan:</b> Funding, cheesecake, not coming over to the gym. </li>
    <li><b>Darren:</b> Answering questions about JS. </li>
    <li><b>Ruth Bader Ginsburg:</b> Logan's favorite person. RIP 😭 </li>
    <li><b>The VA:</b> Providing steps for Logan t̷o̴ k̴̮̒̑͠ī̴̺̂̈́l̸̪̫̽l̴̝͆ ̷̲͍͒̿̓ḥ̶̛̏͜͝i̶̜̬͑̇m̵̠̟̽s̷͔͒e̷͎̼͂̓̀͜l̵̼̘͒f̴͙̙̐ ̴̠̟́͑͝ö̵͖̱́̍̾n̸͚̯͂̌͠.̴̺͍̔͆. </li>
    <li><b>Logan:</b> For serving us. </li>
  </ul>

  <p style="font-size:1vmin"> <a href="https://github.com/caverage/thankloganforserving.us">Source</a>
</div>
</div>
</div>
</div>